/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedAvatarSelectRouteImport } from './routes/_authenticated/avatar-select'
import { Route as AuthenticatedSpaceIndexRouteImport } from './routes/_authenticated/space/index'
import { Route as AuthenticatedUserAvatarSelectRouteImport } from './routes/_authenticated/user/avatar-select'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvatarSelectRoute =
  AuthenticatedAvatarSelectRouteImport.update({
    id: '/avatar-select',
    path: '/avatar-select',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpaceIndexRoute = AuthenticatedSpaceIndexRouteImport.update({
  id: '/space/',
  path: '/space/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserAvatarSelectRoute =
  AuthenticatedUserAvatarSelectRouteImport.update({
    id: '/user/avatar-select',
    path: '/user/avatar-select',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar-select': typeof AuthenticatedAvatarSelectRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/user/avatar-select': typeof AuthenticatedUserAvatarSelectRoute
  '/space/': typeof AuthenticatedSpaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar-select': typeof AuthenticatedAvatarSelectRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
  '/user/avatar-select': typeof AuthenticatedUserAvatarSelectRoute
  '/space': typeof AuthenticatedSpaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/avatar-select': typeof AuthenticatedAvatarSelectRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/user/avatar-select': typeof AuthenticatedUserAvatarSelectRoute
  '/_authenticated/space/': typeof AuthenticatedSpaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar-select'
    | '/auth/login'
    | '/auth/register'
    | '/auth/'
    | '/user/avatar-select'
    | '/space/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar-select'
    | '/auth/login'
    | '/auth/register'
    | '/auth'
    | '/user/avatar-select'
    | '/space'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/avatar-select'
    | '/auth/login'
    | '/auth/register'
    | '/auth/'
    | '/_authenticated/user/avatar-select'
    | '/_authenticated/space/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avatar-select': {
      id: '/_authenticated/avatar-select'
      path: '/avatar-select'
      fullPath: '/avatar-select'
      preLoaderRoute: typeof AuthenticatedAvatarSelectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/space/': {
      id: '/_authenticated/space/'
      path: '/space'
      fullPath: '/space/'
      preLoaderRoute: typeof AuthenticatedSpaceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/avatar-select': {
      id: '/_authenticated/user/avatar-select'
      path: '/user/avatar-select'
      fullPath: '/user/avatar-select'
      preLoaderRoute: typeof AuthenticatedUserAvatarSelectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAvatarSelectRoute: typeof AuthenticatedAvatarSelectRoute
  AuthenticatedUserAvatarSelectRoute: typeof AuthenticatedUserAvatarSelectRoute
  AuthenticatedSpaceIndexRoute: typeof AuthenticatedSpaceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAvatarSelectRoute: AuthenticatedAvatarSelectRoute,
  AuthenticatedUserAvatarSelectRoute: AuthenticatedUserAvatarSelectRoute,
  AuthenticatedSpaceIndexRoute: AuthenticatedSpaceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
